package floatingcube.pointofsale.models;

/**
 * Created by Steven Nguyen on 8/4/2016.
 */
import com.activeandroid.Model;
import com.activeandroid.annotation.Column;
import com.activeandroid.annotation.Table;
import com.activeandroid.query.Select;

import java.util.List;

/**
 * Created by Hieu on 05/08/2016.
 */

@Table(name = "Customers")
public class CustomerModel extends Model {
    // don't put customer_id here, because it is auto generated by active android

    @Column(name = "customer_name")
    public String customerName;

    @Column(name = "customer_email")
    public String customerEmail;

}
